[FEAT]: DARK THEME ADDED TO BOOKBRAINZ WEBSITE
metabrainz/bookbrainz-site pull request #1015
Opened 2023-09-10 14:24 UTC by Thuraabtech

[FEAT]: DARK MODE THEME ADDED TO BOOKBRAINZ WEBSITE
### BB-611

### PROBLEM
THE BOOKBRAINZ WEBSITE DIDN'T HAVE THE DARK THEME MODE

### BB-611
ADDED A FEATURE TO THE BOOKBRAINZ WEBSITE FOR DARK THEME MODE 
WEBSITE ON DARK THEME MODE
<img width="1437" alt="Screenshot 2023-09-10 at 7 51 56 PM" src="https://github.com/metabrainz/bookbrainz-site/assets/97426541/357c923c-20ce-4dc5-abcb-366c286dd0f0">

WEBSITE ON LIGHT THEME MODE
<img width="1430" alt="Screenshot 2023-09-10 at 7 51 40 PM" src="https://github.com/metabrainz/bookbrainz-site/assets/97426541/293c3777-76a7-44a4-a8d3-f1ae02453a17">

### Areas of Impact
THE /bookbrainz-site/src/client/stylesheets/style.scss code has been modified

2023-09-11 12:13 UTC, MonkeyDo requested changes
Thank for opening your first PR! :)

I see in the screenshots that you have not fully set up your local environment (the error "role postgres doesn't exist" means you haven't [initialized your database](https://bookbrainz-dev-docs.readthedocs.io/en/latest/docs/installation.html#database-set-up)).

I would not be confident of this PR if you have only tested how it looks on the error page !
Please  finish your local set up and make sure you test all the pages.

The styles also seem much, much too simple.
For example in your screenshot, the navbar is still a bright white background.
I assume you will find many such issues once you test each page.

2023-09-11 16:06 UTC, Thuraabtech commented on src/client/stylesheets/style.scss
> +<<<<<<< HEAD
thanks for pointing out the mistake , will definately look at the conflict . thats what i was thinking how did this come in the code , got to learn somehing new

2023-10-09 16:41 UTC, MonkeyDo commented
Closing this for inactivity, and considering most of the work is missing.
Please feel free to reopen if and when you have made progress on the issue.

I'm here to help if you have questions or want help getting set up !

2023-10-09 16:41 UTC, closed without merging

2023-10-10 01:23 UTC, Thuraabtech commented
Yeah sure will work on it, I just wanna know where is the main js file

2023-10-10 16:42 UTC, MonkeyDo commented
There is no main js file per se.
It's a big project with many pages, with server code in src/server and client-side code in src/client