BB-766:Empty identifiers/aliases prevent submission of an entity
metabrainz/bookbrainz-site pull request #1048
Opened 2024-01-01 20:39 UTC by insane-22

### Problem
BB-766 Empty identifiers/aliases prevent submission of an entity

### Solution
 
The "Next" Button gets disabled on the third page due to the formValid check:-
![image](https://github.com/metabrainz/bookbrainz-site/assets/116253210/22e21131-f11f-45e4-8e0f-5c14ff162e99)

The formValid property is set using checks on isCoverTabEmpty and validateCoverTab:-
![image](https://github.com/metabrainz/bookbrainz-site/assets/116253210/aaf570d9-242b-45bc-91be-4618007affbd)

On inspecting isCoverTabEmpty, I found that in order to be able to consider form valid even if no identifiers is present, this line shouldn't be present
![image](https://github.com/metabrainz/bookbrainz-site/assets/116253210/3b84167c-5beb-42e9-9eb4-fafd4a18e30c)

Also, since Identifiers are not compulsary, its validation should also not be compulsary:-
![image](https://github.com/metabrainz/bookbrainz-site/assets/116253210/a346c13f-aa00-4769-b7aa-457236f06fa2)

### Areas of Impact

I removed the check on size of Identifiers and changed the validation from compulsary to only when any identifier is present
![image](https://github.com/metabrainz/bookbrainz-site/assets/116253210/bd40ff1f-496b-4ed7-88fc-160c203058b9)

2024-01-01 20:43 UTC, insane-22 commented
This is my first time contributing to bookbrainz and I am quite new to open source. Tried fixing this bug, hope this helps.
If there are any problems with the solution or implementation, please guide me further.
Thank you for your consideration!

2024-01-12 16:26 UTC, MonkeyDo requested changes
Hi @insane-22 thanks for opening a PR!

The root issue is not the one you identified. In fact it is not related to this specific form with he tabs, and you can replicate the same issue for example trying to create a [new work entity](https://test.bookbrainz.org/work/create):

1. fill in the name, sort name and language (which are required) and see that the submit button should be green
2. open the identifier editor and select a type but enter no value. Close the editor
3. see that the submit button is now greyed out

The real issue here is that an identifier with a type selected but no value entered should automatically be discarded and ignored rather than fail validation of the whole form.

I think the easy way to resolve this at this point in time would be to remove identifiers with a type selected but no value. We currently already remove entirely empty rows here, so it's probably as simple as removing ` && identifier.get('type') === null)` here, then finding a similar solution for the aliases editor:
https://github.com/metabrainz/bookbrainz-site/blob/c47025006298d28a7720e779f75bf6d2fcfc0253/src/client/entity-editor/identifier-editor/reducer.ts#L59-L61



Do let me know if you need any assistance.

2024-01-12 16:26 UTC, MonkeyDo commented on src/client/unified-form/validators/cover-tab.ts
> -    size(identifierEditor) === 0 &&
I don't think this should be removed.
This function checks if the cover tab is empty, which should indeed be false if the user has input an ISBN or any other identifier.

2024-01-12 17:00 UTC, insane-22 commented
Ahh, I realised i misunderstood the isssue completely and hence the solution too is incorrect (infact not of the required problem). Allow me sometime to look into this and see if I could help with my contribution.
Thanks a lot for your invaluable guidance!

2024-01-12 17:29 UTC, insane-22 commented
> The real issue here is that an identifier with a type selected but no value entered should automatically be discarded and ignored rather than fail validation of the whole form.
 
I guess rather than removing  `&& identifier.get('type') === null)` , it should be `||  identifier.get('type') === null)` so that the row is considered empty when either the value or type of identier is not provided, what do you think?

2024-01-15 17:06 UTC, MonkeyDo commented
> > The real issue here is that an identifier with a type selected but no value entered should automatically be discarded and ignored rather than fail validation of the whole form.
> 
> I guess rather than removing `&& identifier.get('type') === null)` , it should be `|| identifier.get('type') === null)` so that the row is considered empty when either the value or type of identifier is not provided, what do you think?

No, I think we probably want to keep rows where the user tried to enter some information but might be incomplete (i.e. tried to paste a link, but auto-detection didn't work or something like that).
My reasoning being that we don't want to frustrate our users by deleting information they entered. I think the type selection in a drop-down does not qualify as information we want to preserve, so that check can just be removed.

2024-01-16 17:27 UTC, insane-22 commented
> > > The real issue here is that an identifier with a type selected but no value entered should automatically be discarded and ignored rather than fail validation of the whole form.
> > 
> > 
> > I guess rather than removing `&& identifier.get('type') === null)` , it should be `|| identifier.get('type') === null)` so that the row is considered empty when either the value or type of identifier is not provided, what do you think?
> 
> No, I think we probably want to keep rows where the user tried to enter some information but might be incomplete (i.e. tried to paste a link, but auto-detection didn't work or something like that). My reasoning being that we don't want to frustrate our users by deleting information they entered. I think the type selection in a drop-down does not qualify as information we want to preserve, so that check can just be removed.

Ok, got it!
I do agree removing name may cause a bad user experience. Hence, row should be considered empty only when "name" is not provided. Extending similar logic to alias editor, it is updated to be considered empty when name is not provided.

2024-01-16 17:28 UTC, insane-22 commented
I have made the changes, kindly review them and suggest changes if any.

2024-01-16 17:34 UTC, insane-22 commented
Preview:- 

https://github.com/metabrainz/bookbrainz-site/assets/116253210/310d9f7d-802d-40bd-bd8f-087fe6cd8d49

2024-02-21 10:12 UTC, MonkeyDo approved these changes
Great, thank you ! 🚀 

Sorry for the delay in finishing reviewing the PR !

2024-02-21 10:13 UTC, merged