Updated syntax in utils.js with async/await
metabrainz/bookbrainz-site pull request #1146
Opened 2024-12-18 12:23 UTC by moksha-hub

### Problem

Ticket No: #[BB-797]

2024-12-19 08:54 UTC, moksha-hub commented
@MonkeyDo Thanks for your help and guidance, and now my first PR is successfully awaiting approval to be merged. Once again, thank you!

2024-12-31 04:15 UTC, moksha-hub commented
@MonkeyDo i request you to have a look at my pr for any further corrections if needed.

2025-02-27 12:57 UTC, MonkeyDo approved these changes
Sorry for the long delay!

Thanks for rewriting this file, works like a charm! :rocket: 

I took the liberty of adding back the documentation for the allowOnlyGetMethod function, which I assumed were deleted by mistake.

2025-02-27 15:40 UTC, MonkeyDo commented
@moksha-hub for ease of work, you can run the linting on your local machine and avoid the back-and-forth, with the command yarn run lint
See installation guide if needed: https://bookbrainz-dev-docs.readthedocs.io/en/latest/docs/installation.html

2025-02-27 15:47 UTC, moksha-hub commented
I sincerely apologize for the multiple attempts. I appreciate your patience and understanding. Can you please check it now? Thank you for your time!

2025-02-27 15:48 UTC, MonkeyDo commented
No worries about the commits, I will squash it all into one commit when merging. It was more to simplify your own workflow :)
Will check again now.

2025-02-27 15:56 UTC, MonkeyDo requested changes
Just a couple of minor details, some just linting warnings (not even errors).
After that, clear for merging ! :)

2025-02-27 15:56 UTC, MonkeyDo commented on src/api/helpers/utils.js
> +		const errorMessage = 'Failed to fetch browsed relationships';
It could be helpful to have the full error message here for debugging purposes:
```suggestion
		const errorMessage = `Failed to fetch browsed relationships: ${error.toString()}`;
```

2025-02-27 15:56 UTC, MonkeyDo commented on src/api/helpers/utils.js
> -
These two lines shouldn't be removed, it created an ESLint warning
"Expected 2 empty lines after import statement not followed by another import (import/newline-after-import)"

2025-02-27 15:56 UTC, MonkeyDo commented on src/api/helpers/utils.js
> +export const relationshipsRelations = ['relationshipSet.relationships.type']; // Fixed from 'relationship' to 'relationships'
I don't think the comment is required here, unless I missed something.
As it is creating an ESLint warning, let's remove it.
```suggestion
export const relationshipsRelations = ['relationshipSet.relationships.type'];
```

2025-02-27 16:01 UTC, MonkeyDo commented
See I messed up with fixing the test suite as well :)

2026-04-22 02:50 UTC, closed without merging