Fix(editor): Error handling for not found editor
metabrainz/bookbrainz-site pull request #815
Opened 2022-03-17 04:52 UTC by tr1ten

### Problem

Since function execution doesn't stop after next(err) thus causing issues

Relevant ticket BB-651: 502 when trying to load an editor by name

### Areas of Impact

editor route

2022-03-22 18:44 UTC, MonkeyDo requested changes
We're slowly moving the codebase to use async/await wherever we can, so I don't want us to revert to using promise chains.

I believe what is missing is a `try {…} catch(err) {next(err)}`  block around the meat of the query, wrapping around the lines from `const editorJSONPromise`  to `res.send(target({…}));`

Finally in this route we should remove the instances of `.catch(next)`; since we wrap the whole thing, we want errors to bubble up to our main try-catch block and call `next` in the catch part.

Do let me know if I wasn't clear :)

2022-03-22 18:44 UTC, MonkeyDo commented on src/server/routes/editor.js
> +	}
Yes, let's keep this !

2022-03-23 11:48 UTC, tr1ten commented
I wonder, in general what would be more efficient- awaiting on each promise or awaiting on promise.all, any difference performance wise?

2022-03-23 16:22 UTC, MonkeyDo approved these changes
Thank you !
That fixes that issue !

2022-03-23 16:23 UTC, merged