BB-671: Refactoring statistics.js
metabrainz/bookbrainz-site pull request #954
Opened 2023-03-11 14:58 UTC by meziyum

### Problem [BB-671](https://tickets.metabrainz.org/browse/BB-671)
Across the codebase we have asynchronous code written using promises, which is hard to read and to maintain and error-prone.

All this code needs to be rewritten using the async/await syntax.

### Solution
The route has been refactored to use async/await syntax for better error handing, maintainability and readability. The parts of the code have also been modularized for better readability and maintainability. 

### Areas of Impact
Statistics - [Statistics Route](https://github.com/metabrainz/bookbrainz-site/blob/master/src/server/routes/statistics.js)

2023-03-16 14:15 UTC, MonkeyDo requested changes
Great work, thank you !
In particular, 10 extra points for the nice documentation improvements !

One single small bit of feedback:

2023-03-16 18:31 UTC, meziyum commented on src/server/routes/statistics.js
> +	const entityModels = commonUtils.getEntityModels(orm);
I have no idea how I missed that one 🥲 
Apologies for the commits being all over the place.
I would make sure for them to be in proper order in the future.

2023-03-17 10:29 UTC, MonkeyDo commented on src/server/routes/statistics.js
> +	const entityModels = commonUtils.getEntityModels(orm);
Don't worry about it too much, that's why we do code reviews :)

As for commits, if the issue is with tests and code linting, you can run commands on your computer to run the tests and make sure the code is formatted appropriately:

- `npm run test` to run the whole test suite
- `npm run test path/to/file/or/folder` to run a specific test file or folder
- `npm run lint` will show you if there are any code formatting issues

2023-03-17 10:30 UTC, MonkeyDo approved these changes
Great work, thank you !

2023-03-17 10:42 UTC, merged